apiVersion: v1
appVersion: 1.6.17
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/master/images/java.png
name: dukecon-server
version: 1.6.17
